'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''_Default class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class _Default

   '''<summary>
   '''form1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''HyperLink1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

   '''<summary>
   '''HyperLink2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents HyperLink2 As Global.System.Web.UI.WebControls.HyperLink

   '''<summary>
   '''txtWidth control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''txtHeight control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtHeight As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''txtQuality control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtQuality As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''lnkResize control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lnkResize As Global.System.Web.UI.WebControls.LinkButton

   '''<summary>
   '''lnkSave control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.LinkButton

   '''<summary>
   '''plhResize control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents plhResize As Global.System.Web.UI.WebControls.PlaceHolder
End Class
