'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''DrillDown class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class DrillDown

   '''<summary>
   '''form1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''mvDrillDown control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents mvDrillDown As Global.System.Web.UI.WebControls.MultiView

   '''<summary>
   '''vUsers control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents vUsers As Global.System.Web.UI.WebControls.View

   '''<summary>
   '''dlstUsers control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dlstUsers As Global.System.Web.UI.WebControls.DataList

   '''<summary>
   '''vAlbums control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents vAlbums As Global.System.Web.UI.WebControls.View

   '''<summary>
   '''lnkUserList control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lnkUserList As Global.System.Web.UI.WebControls.LinkButton

   '''<summary>
   '''lblResults control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblResults As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''dlstAlbums control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dlstAlbums As Global.System.Web.UI.WebControls.DataList

   '''<summary>
   '''vPictures control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents vPictures As Global.System.Web.UI.WebControls.View

   '''<summary>
   '''lnkUserList2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lnkUserList2 As Global.System.Web.UI.WebControls.LinkButton

   '''<summary>
   '''hlnkBackToAlbums control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hlnkBackToAlbums As Global.System.Web.UI.WebControls.HyperLink

   '''<summary>
   '''gvPictures control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents gvPictures As Global.System.Web.UI.WebControls.GridView

   '''<summary>
   '''vComments control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents vComments As Global.System.Web.UI.WebControls.View

   '''<summary>
   '''lnkUserList3 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lnkUserList3 As Global.System.Web.UI.WebControls.LinkButton

   '''<summary>
   '''lblCommentCount control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblCommentCount As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''gvComments control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents gvComments As Global.System.Web.UI.WebControls.GridView
End Class
